use_dev_config: False

ade20k:
  root_dir: "/media/rafi/Samsung_T5/_DATASETS/ADE20K/"
  caption_dir: "/media/rafi/Samsung_T5/_DATASETS/ADE20K/image-description-sequences/data/"

captioning:
  catr:
    cuda_device: "cuda:0"
    beam_size: 1
  sentence_bert:
    cuda_device: "cuda:0"
    model: "paraphrase-MiniLM-L6-v2"
output_dir: "/home/rafi/PycharmProjects/clp-sose21-pm-vision/results"

game_setup:
  game_logs_dir: "/home/users/alatif/project/sose21-pm-language-and-vision-g1/data/game_logs/"
  map:
    size: 4
    ambiguity: 2
    rooms: 8
  avatar:
    room_list: 100 #in percent, defines the number of rooms it should get from the game master
    include_player_room: True # Boolean True or False ,defines if the room where the player is stuck should be included or not
    max_number_of_interaction: 3 # Defines the number of interactions a player is allowed to have
    similarity_threshold: 0.57 # If during the allowed number of interactions, the robot identifies any images over this threshold, it stops the game to give it a try.
    minimum_similarity_threshold: 0.53  # This is the bare minimum to for the robot to say that it has some clues about the rooms. Otherwise it says it hasn t seen the room.
    aggregate_interaction: True # Boolean True or False. Decides whether all player description are merged to one big description
  debug: True # Boolean True or False, output some more messages


