use_dev_config: False

ade20k:
  root_dir: "/media/rafi/Samsung_T5/_DATASETS/ADE20K/"
  caption_dir: "/media/rafi/Samsung_T5/_DATASETS/ADE20K/image-description-sequences/data/"

captioning:
  catr:
    cuda_device: "cuda:0"
    beam_size: 1

output_dir: "/home/rafi/PycharmProjects/clp-sose21-pm-vision/results"

game_setup:
  game_logs_dir: "/home/users/alatif/project/sose21-pm-language-and-vision-g1/data/game_logs/"
  map:
    size: 4
    ambiguity: 2
    rooms: 8
  avatar:
    room_list: 100 #in percent, defines the number of rooms it should get from the game master
    include_player_room: True # Boolean True or False ,defines if the room where the player is stuck should be included or not
    max_number_of_interaction: 3 # Defines the number of interactions a player is allowed to have
  debug: True # Boolean True or False, output some more messages


